# This block tells Uffizzi which service should receive HTTP traffic.
x-uffizzi:
  ingress:
    service: app
    port: 3000

# Argo-X images
services:
  app:
    image: fscarmen/argo-x:latest
    restart: always
    environment:
      WSPATH: argo
      UUID: dc3a3911-e4ab-48ac-9473-fde427bdaa49
      # NEZHA_KEY: vXzZLTaBU3oVO9pyM
      # NEZHA_SERVER: probe.nezha.org
      #N EZHA_PORT: 5555
